//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DekorWPf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id_Product { get; set; }
        public string Article { get; set; }
        public string Name_Product { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Sale { get; set; }
        public int id_Manufacturer { get; set; }
        public int id_Supplier { get; set; }
        public int id_Categories { get; set; }
        public Nullable<int> Sale_Now { get; set; }
        public Nullable<int> Quantity_angar { get; set; }
        public string Description { get; set; }
        public string Image_product { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
