USE [master]
GO

/****** Object:  Database [DekorDB]    Script Date: 21.03.2023 19:03:48 ******/
CREATE DATABASE [DekorDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DekorDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERV1215\MSSQL\DATA\DekorDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DekorDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERV1215\MSSQL\DATA\DekorDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DekorDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DekorDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DekorDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DekorDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DekorDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DekorDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DekorDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DekorDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DekorDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DekorDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DekorDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DekorDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DekorDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DekorDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DekorDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DekorDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DekorDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DekorDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DekorDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DekorDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DekorDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DekorDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DekorDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DekorDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DekorDB] SET  MULTI_USER 
GO

ALTER DATABASE [DekorDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DekorDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DekorDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DekorDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DekorDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DekorDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DekorDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DekorDB] SET  READ_WRITE 
GO

